name: Arduino Hardware Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hw-test:
    runs-on: self-hosted

    steps:

      - name: Debug PATH
        run: echo $Env:Path

      - name: Install arduino-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python2 Dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile Arduino Code
        run: |
          C:\Users\kgupta\HIL-1\arduino-cli compile --fqbn arduino:avr:uno blink_test

      - name: Upload Sketch to Arduino
        run: |
          C:\Users\kgupta\HIL-1\arduino-cli upload -p COM7 --fqbn arduino:avr:uno blink_test

      - name: Run Python Hardware Tests
        run: |
          python test_arduino.py